add_rules("mode.release")

add_requires("freeglut", "xerces-c")

target("Ateams_Base")
	set_kind("static")
	set_languages("c++17")
	add_headerfiles("Ateams_Base/src/*.hpp")
	add_files("Ateams_Base/src/*.cpp")
	add_packages("freeglut", "xerces-c")
	set_toolchains("mingw")

target("BinPacking")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("BinPacking/src/*.hpp")
	add_files("BinPacking/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")

target("FlowShop")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("FlowShop/src/*.hpp")
	add_files("FlowShop/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")

target("GraphColoring")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("GraphColoring/src/*.hpp")
	add_files("GraphColoring/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")

target("JobShop")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("JobShop/src/*.hpp")
	add_files("JobShop/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")

target("KnapSack")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("KnapSack/src/*.hpp")
	add_files("KnapSack/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")

target("TravellingSalesman")
	set_kind("binary")
	set_languages("c++17")
	add_headerfiles("TravellingSalesman/src/*.hpp")
	add_files("TravellingSalesman/src/*.cpp")
	add_deps("Ateams_Base")
	set_toolchains("mingw")
